### ISSUE TITLE
Filebeat indices not created

### ISSUE THREAD

**Issue by mgreau** [mgreau/tekton-pipelines-elastic-tutorials#2]
Some people who followed the hello-world tutorial can't see the logs in the Infrastructure Logs UI
<img width="518" alt="screen shot 2019-01-18 at 16 37 52" src="https://user-images.githubusercontent.com/501525/51740817-664c4080-2095-11e9-8ca7-f67769f5e95e.png">

## Environment

* Docker for Desktop edge
```
Docker Engine - Community
Version:           18.09.1

Kubernetes: v1.13.0
```

## Context

All the pods are running:

```
kubectl get pods

NAME                                  READY   STATUS    RESTARTS   AGE
elasticsearch-789fb5c945-9k2j6        1/1     Running   0          79m
filebeat-lxvst                        1/1     Running   0          79m
kibana-75bfff54d4-h5t7j               1/1     Running   0          79m
kube-state-metrics-5877d79cdc-r7rc5   1/1     Running   0          79m
metricbeat-mxtzj                      1/1     Running   0          79m

``` 

It turned out that the Filebeat indices have not been created:
<img width="1221" alt="screen shot 2019-01-22 at 10 50 19" src="https://user-images.githubusercontent.com/501525/51740978-dce93e00-2095-11e9-9997-5294b545fe47.png">

The pods logs are attached:
* [eslogs.log](https://github.com/mgreau/knative-elastic-tutorials/files/2795693/eslogs.log)

* [filebeatlogs.log](https://github.com/mgreau/knative-elastic-tutorials/files/2795689/filebeatlogs.log)
* [metricbeatlogs.log](https://github.com/mgreau/knative-elastic-tutorials/files/2795692/metricbeatlogs.log)

**Comment by mgreau** [comment]
> Docker Engine - Community
 Version:           18.09.1
  Kubernetes: v1.13.0

I have upgraded my Docker for Desktop version to use the exact same configuration and it works for me.

**Comment by exekias** [comment]
I see an error in the logs:

```
2019-01-18T16:14:26.784Z        ERROR   kubernetes/util.go:90   kubernetes: Querying for pod failed with error: kubernetes api: Failure 404 pods "docker-desktop" not found
```

You can avoid this problem by passing the actual node name, check latest manifests at https://github.com/elastic/beats/blob/1942cc2237f32644d099254d7118fc4623643898/deploy/kubernetes/metricbeat-kubernetes.yaml#L126-L129

We take the `spec.nodeName` into `NODE_NAME` env var, then use it as the `host` setting for autodiscover or `add_kubernetes_metadata`.

You can update https://github.com/mgreau/knative-elastic-tutorials/blob/1b2383b5bb8212c43b895ed6f7abbe58d0b678f5/pipeline-elastic/config/04-elastic-metricbeat.yaml#L64, and do the same with Filebeat

**Comment by jessm12** [comment]
Thanks @exekias, I think have tried as you suggested but have seen no change, updating the files:

`04-elastic-metricbeat.yaml` and `03-elastic-filebeat.yaml` with the value `host: docker-desktop`, is this what you were describing to change?

**Comment by exekias** [comment]
You would need to add this first https://github.com/elastic/beats/blob/1942cc2237f32644d099254d7118fc4623643898/deploy/kubernetes/metricbeat-kubernetes.yaml#L126-L129:
```
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

and then use `host: ${NODE_NAME}`

`docker-desktop` may not always be the name of the node

**Comment by mgreau** [comment]
@jessm12 I'm working on a fix
